---
name: step
version: 17.08.1
summary: Simulate physics experiments
description: |-
    Step is an interactive physical simulator. It allows you to explore the physical world through simulations. It works like this: you place some bodies on the scene, add some forces such as gravity or springs, then click Simulate and Step shows you how your scene will evolve according to the laws of physics. You can change every property of the bodies/forces in your experiment (even during simulation) and see how this will change evolution of the experiment. With Step you cannot only learn but feel how physics works!

    Features:

    - Classical mechanical simulation in two dimensions
    - Particles, springs with damping, gravitational and coulomb forces
    - Rigid bodies
    - Collision detection (currently only discrete) and handling
    - Soft (deformable) bodies simulated as user-editable particles-springs system, sound waves
    - Molecular dynamics (currently using Lennard-Jones potential): gas and liquid, condensation and evaporation, calculation of macroscopic quantities and their variances
    - Units conversion and expression calculation: you can enter something like "(2 days + 3 hours) \* 80 km/h" and it will be accepted as distance value (requires libqalculate)
    - Errors calculation and propagation: you can enter values like "1.3 ± 0.2" for any property and errors for all dependent properties will be calculated using statistical formulas
    - Solver error estimation: errors introduced by the solver is calculated and added to user-entered errors
    - Several different solvers: up to 8th order, explicit and implicit, with or without adaptive timestep (most of the solvers require GSL library)
    - Controller tool to easily control properties during simulation (even with custom keyboard shortcuts)
    - Tools to visualize results: graph, meter, tracer
    - Context information for all objects, integrated wikipedia browser
    - Collection of example experiments, more can be downloaded with KNewStuff
    - Integrated tutorials
confinement: strict
grade: stable
apps:
    step:
        command: kf5-launch step
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.step
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    step:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libeigen3-dev
        - libglib2.0-dev
        - libgsl-dev
        - libkf5kdelibs4support-dev
        - libkf5khtml-dev
        - libqalculate-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/step-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
